default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: loamy_api_local
    username: dylanrunkel
    password: <%= ENV["APP_DATABASE_PASSWORD"] %>
  queue:
    <<: *default
    database: loamy_api_local_queue
    migrations_paths: db/queue_migrate


test:
  primary:
    adapter: sqlite3
    database: db/test.sqlite3
  queue:
    adapter: sqlite3
    database: db/test-queue.sqlite3
    migrations_paths: db/queue_migrate

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  queue:
    <<: *primary_production
    migrations_paths: db/queue_migrate
